function flux_linkage = Flux_linkage_calculation_based_on_linear_FEM(PMSM_Flux_linkage_Test)
% This function is used to calculate the flux-linkage generated by PM based
% on the linear finite element model
import Winding_Matrix_Package.*;
import Air_gap_Package.*;
import Rotor_Package.*;
import Stator_Package.*;
import Windings_Package.*;

%% Create the engineers
design_engineer = MotorDesignEngineer();
test_engineer = MotorTestEngineer();

%% Create the VPM_Slotless in the femm (single test)
PMSM_Flux_linkage_Test.documentsaddress = '.\femm documents';
PMSM_Flux_linkage_Test.create_femm();
design_engineer.builder = PMSM_Flux_linkage_Test.rotor;
design_engineer.construct();
design_engineer.builder = PMSM_Flux_linkage_Test.air_gap;
design_engineer.construct();
design_engineer.builder = PMSM_Flux_linkage_Test.stator;
design_engineer.construct();
design_engineer.builder = PMSM_Flux_linkage_Test.windings;
design_engineer.construct();
PMSM_Flux_linkage_Test.close_femm();

%% Define the Testproject of Motor
Motor_flag = 1;
% Motor_flag == 1, 转子反向旋转; clockwise
% Motor_flag == 2, 转子正向旋转; anticlockwise
Rotor_flag = 2;
% Rotor_flag ==1, outer rotor;
% Rotor_flag ==2, inner rotor;

% define some test parameters of Flux linkage Test
fluxlinkage_test = FluxTest();
fluxlinkage_test.documentsaddress = '.\figure documents\Flux linkage';
fluxlinkage_test.theta_min_deg = 0;
fluxlinkage_test.theta_max_deg = 350;
fluxlinkage_test.dtheta_deg = 10;
fluxlinkage_test.Motor_flag = Motor_flag;
% Motor_flag == 1, clockwise;
% Motor_flag == 2, anticlockwise;
fluxlinkage_test.Rotor_flag = Rotor_flag;
% Rotor_flag ==1, outer rotor;
% Rotor_flag ==2, inner rotor;

 %% Flux_PM Test
 fluxlinkage_test.testmotor = PMSM_Flux_linkage_Test;
 test_engineer.testproject = fluxlinkage_test;
 test_engineer.test();
 flux_linkage_of_phase = fluxlinkage_test.flux_PM;
 size_of_theta = round(fluxlinkage_test.theta_max_deg-fluxlinkage_test.theta_min_deg)/fluxlinkage_test.dtheta_deg+1;
 [~, Phi] = FFT(flux_linkage_of_phase, size_of_theta);
phim = Phi(2);
flux_linkage = phim;


end

